name: typo3-testing
type: typo3
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "8080"
router_https_port: "8081"
xdebug_enabled: false
additional_hostnames:
  - "typo3-testing-en"
additional_fqdns: [ ]
mariadb_version: "10.5"
mysql_version: ""
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2.1.5"
web_environment: [ ]

# This config.yaml was created with ddev version v1.17.7
