version: "3.6"
services:
  web:
    environment:
      - TZ=Europe/Berlin

      - TYPO3_INSTALL_DB_DRIVER=mysqli
      - TYPO3_INSTALL_DB_USER=db
      - TYPO3_INSTALL_DB_PASSWORD=db
      - TYPO3_INSTALL_DB_HOST=db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_UNIX_SOCKET=
      - TYPO3_INSTALL_DB_USE_EXISTING=1
      - TYPO3_INSTALL_ADMIN_USER=admin
      - TYPO3_INSTALL_ADMIN_PASSWORD=password
      - TYPO3_INSTALL_SITE_NAME=TYPO3 testing site
      - TYPO3_INSTALL_SITE_SETUP_TYPE=none
      - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
